### ISSUE TITLE
Is this project still active and maintained？

### ISSUE THREAD

**Issue by tuhao1020** [alibaba/sentinel-golang#416]
the last issue is created at 31 May and the last version released at 14 Jan,  commits per month is less than 5 for the past 6 months.

**Comment by tylitianrui** [comment]
waitting to be answered  too

**Comment by sczyh30** [comment]
Yes. We're planning the nouveau Sentinel 2.0 these months (we'd like Sentinel Go to be a cloud-native infra instead of just a lib). Discussions are welcomed at https://github.com/alibaba/sentinel-golang/discussions/399

Also refer: 

- https://github.com/alibaba/sentinel-golang/wiki/Sentinel-2.0-形态构想
- https://github.com/sentinel-group/sentinel-policy-brain

**Comment by tuhao1020** [comment]
thx for your reply, looking forward to the version 2.0
